name: bill_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  flutter:
    sdk: flutter
  bill:
    path: ../bill
  bill_rest_api:
    path: ../bill_rest_api
  bill_sqflite_api:
    path: ../bill_sqflite_api
  settings_shared_api:
    path: ../settings_shared_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
